### ISSUE TITLE
Sonar plugin finds issues but when it shows on dashboard files are not shown.

### ISSUE THREAD

**Issue by dixitmehuls** [stepstone-tech/sonar-coldfusion#20]
![image](https://user-images.githubusercontent.com/7084445/33850644-846751f0-de82-11e7-96aa-8b1ee999bab9.png)

![image](https://user-images.githubusercontent.com/7084445/33850675-a36e7fba-de82-11e7-9170-755704966863.png)
![image](https://user-images.githubusercontent.com/7084445/33850689-b3a70640-de82-11e7-986d-efa3003b95de.png)

14:38:20.090 DEBUG: Language of file 'SPDR/index.cfm' is detected to be 'cf'
14:38:20.099 INFO: 239 files indexed
14:38:20.117 INFO: Quality profile for cf: Sonar way (rest all files are cfm)
14:38:20.117 INFO: Quality profile for css: Sonar way (1 file)
14:38:20.117 INFO: Quality profile for js: Sonar way (28 files)

14:38:26.849 INFO: Sensor null (wrapped)
14:38:31.711 ERROR: line 2:4 no viable alternative at input '<cfelse'
14:38:31.712 ERROR: line 3:5 no viable alternative at input '<cfset'
14:38:31.715 ERROR: line 3:11 mismatched input 'strSql' expecting <EOF>
14:38:31.716 ERROR: null
14:38:31.717 ERROR: Error in:     <cfset strSql = " and A.FE_TRK_SOURCE_CODE  #REReplace(legac,"''","'","All")#  "> @ 128:
14:38:31.717 ERROR: null
14:38:32.259 ERROR: line 2:5 no viable alternative at input '<cfset'
14:38:32.259 ERROR: line 2:11 mismatched input 'strSql1' expecting <EOF>
14:38:32.259 ERROR: null
14:38:32.260 ERROR: Error in:     <cfset strSql = " and A.FE_TRK_SOURCE_CODE  #REReplace(legac,"''","'","All")#  "> @ 165:
14:38:32.260 ERROR: null
14:38:32.260 ERROR: line 2:5 no viable alternative at input '<cfset'
14:38:32.261 ERROR: line 2:11 mismatched input 'strSql1' expecting <EOF>
14:38:32.261 ERROR: null
14:38:32.261 ERROR: Error in:     <cfset strSql = " and A.FE_TRK_BILLER_CODE  #REReplace(legac,"''","'","All")#  "> @ 168:
14:38:32.261 ERROR: null
14:38:47.975 INFO: Sensor null (wrapped) (done) | time=21126ms

I can go to issues and still see issues :)

![image](https://user-images.githubusercontent.com/7084445/33850857-39a82b98-de83-11e7-8203-34992df7273c.png)

**Comment by tommywo** [comment]
this was probably related to plugin not providing NLOC metric. I don't see the issue now
