### ISSUE TITLE
SonarQube 7.9.1 Compatability

### ISSUE THREAD

**Issue by mxtyl** [stepstone-tech/sonar-coldfusion#25]
Could you please update the plugin to be compliant with SonarQube 7.9.1?  Analysis of ColdFusion source doesn't produce any results.

Thanks!

**Comment by OEL-HMC** [comment]
Hello, I have been able to make it work with latest version of sonarQube with the jar listed on https://github.com/ghedwards/sonar-coldfusion/releases/tag/sonar-7.6

I had also to upgrade Xms and Xmx for elastic search to 2g for each to make it work.

**Comment by tommywo** [comment]
SonarQube 7.9 is supported in v2.0.0
