### ISSUE TITLE
Not able to import open cover code coverage report from jenkins server.

### ISSUE THREAD

**Issue by sgaikwad** [stepstone-tech/sonar-coldfusion#9]
Not able to import the open cover code coverage file from jenkins to sonar qube.

I tried using the windows command prompt with the same commands and i am able to import the report.

facing the issue while importing from jenkins.

below are the steps followed:
::Step 1
C:\Softwares\MSBuild.SonarQube.Runner-1.1\MSBuild.SonarQube.Runner.exe begin /k:TestProject_Key /n:TestProject /v:1.0 /d:sonar.cs.opencover.it.reportsPaths="C:\ProjectWork\Alerts\IPSDataOnlyAccess\opencover.xml"

::Step 2
"C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" "C:\ProjectWork\Alerts\IPSDataOnlyAccess\IPSDataOnlyAccess.sln" /t:rebuild

:Step 3
![opencover](https://cloud.githubusercontent.com/assets/4261512/20746572/4afb0e76-b6b4-11e6-8f4c-a9838e76cc08.png)

"C:\Softwares\opencover.4.6.519\OpenCover.Console.exe" -output:"C:\ProjectWork\Alerts\IPSDataOnlyAccess\opencover.xml" -register:path32 -target:"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" -targetargs:"C:\ProjectWork\Alerts\IPSDataOnlyAccess\IPSDataOnlyAccessTest\bin\Debug\IPSDataOnlyAccessTest.dll"

Please help me to over come this issue, i am stuck here.

**Comment by mpaluchowski** [comment]
OpenCover seems to be a code coverage tool for .NET, and _not_ for ColdFusion. This repository is for the ColdFusion plugin for SonarQube and I'm afraid we can't help with OpenCover.

You may want to see with the [OpenCover project](https://github.com/OpenCover/opencover) if they can provide any support.
